services:
  openarc:
    build: .
    restart: unless-stopped
    ports:
      - "8000"
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    volumes:
      - openarc-models:/models
      - openarc-persist:/persist
    environment:
      NEOReadDebugKeys: "1"
      OverrideGpuAddressSpace: "48"
      EnableImplicitScaling: "1"

volumes:
  openarc-models:
  openarc-persist:
